### ISSUE TITLE
How can I get the access to the benchmark?

### ISSUE THREAD

**Issue by kittimzhe** [lifelong-robotic-vision/OpenLORIS-Scene#26]

**Comment by cedrusx** [comment]
Hi @kittimzhe you can check the benchmarking scripts [here](https://github.com/lifelong-robotic-vision/openloris-scene-tools/tree/master/benchmark) or check the IROS 2019 results on the competition webpage https://lifelong-robotic-vision.github.io/competition/slam

**Comment by kittimzhe** [comment]
thank you very much .-. @cedrusx
